name: Deploy Coupon App
on:
  push:
    branches: [ coupon-deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - run: chmod +x gradlew
      - run: ./gradlew build -x test

      - name: Copy JAR & Dockerfile
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_COUPON_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_COUPON_KEY }}
          source: "build/libs/*.jar,Dockerfile"
          target: /home/ec2-user/coupon-app
          strip_components: 2   # hilangkan build/libs

      - name: SSH & deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_COUPON_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_COUPON_KEY }}
          script: |
            set -e
            cd /home/ec2-user/coupon-app
            
            # pilih jar yang tidak mengandung "-plain"
            JAR_FILE=$(ls -t *.jar | grep -v '\-plain' | head -n 1)
            [ -z "$JAR_FILE" ] && { echo "âŒ JAR tidak ditemukan"; exit 1; }
            
            rm -f app.jar
            mv "$JAR_FILE" app.jar
            
            # pastikan Docker ada
            if ! command -v docker &>/dev/null; then
              sudo yum -y update
              sudo yum -y install docker
              sudo systemctl start docker
            fi
            
            sudo docker stop coupon-app || true
            sudo docker rm   coupon-app || true
            sudo docker build -t coupon-app .
            
            # Jalankan dengan env file
            sudo docker run -d -p 80:8080 --name coupon-app \
            --env-file .env \
            coupon-app
